import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBar from "@/contents/navigation/navbar";
import '@/styles/globals.css';

const inter = Inter({ subsets: ["latin"] });
 

export const metadata: Metadata = {
  title: "CarBari - Get Your Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NavigationBar/>
          <main>{children}</main>  
          {/* <Footer/> */}
      </body>
    </html>
  );
}

// global style for main